name: ifa

services:
  postgres:
    image: 'postgres:15'
    restart: always
    expose:
      - '5432'
    ports:
      - '5432:5432'
    environment:
      TZ: UTC
      PGTZ: UTC
      POSTGRES_DB: ifa
      POSTGRES_USER: ifa
      POSTGRES_PASSWORD: password
    volumes:
      - ./db-init-scripts:/docker-entrypoint-initdb.d
