name: ifa

networks:
  ifa:

services:
  postgres:
    image: 'postgres:15'
    restart: always
    expose:
      - '5432'
    ports:
      - '5434:5432'
    networks:
      ifa:
        aliases:
          - postgres
    environment:
      TZ: UTC
      PGTZ: UTC
      POSTGRES_DB: ifa
      POSTGRES_USER: ifa
      POSTGRES_PASSWORD: password
    volumes:
      - .api//target/postgresql:/var/lib/postgresql
      - ./db-init-scripts:/docker-entrypoint-initdb.d
